// frontend-svelte/src/lib/components/InferenceLogger.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { logInference, getAllModelIds } from '$lib/api';

  let { initialModelId = '', onSuccess }: {
    initialModelId?: string;
    onSuccess?: (modelId: string) => void;
  } = $props();

  function randomHash() {
    const buf = new Uint8Array(32);
    crypto.getRandomValues(buf);
    return Array.from(buf).map(b => b.toString(16).padStart(2, '0')).join('');
  }

  let modelId    = $state('');
  let inferenceId = $state('f61c7b91-2e83-4f4a-8c9b-7c0cb90fca1e');
  let input      = $state('a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1');
  let outputHash = $state('d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2');
  let params     = $state('{"threshold": 0.8, "preprocessing": "normalize"}');
  let metadata   = $state('{"dataset": "ChestX-ray14", "framework": "TensorFlow"}');

  let loading  = $state(false);
  let result   = $state<any>(null);
  let error    = $state<string | null>(null);
  let modelIds = $state<string[]>([]);

  onMount(async () => {
    modelId = initialModelId;
    try { modelIds = await getAllModelIds(); } catch { modelIds = []; }
  });

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    loading = true; error = null; result = null;

    try {
      result = await logInference({
        modelId, inferenceId,
        inputHash: input, outputHash,
        params:   params   ? JSON.parse(params)   : {},
        metadata: metadata ? JSON.parse(metadata) : {}
      });
      onSuccess?.(modelId);
    } catch (err: any) {
      error = err.response?.data?.message || err.message || 'Failed to log inference';
    } finally {
      loading = false;
    }
  }
</script>

<div class="max-w-2xl space-y-6">
  <div>
    <h2 class="text-xl font-semibold text-slate-800">Log Inference</h2>
    <p class="text-sm text-slate-500 mt-1">Record a model inference event on the blockchain</p>
  </div>

  <form onsubmit={handleSubmit} class="space-y-4">
    <div>
      <label class="field-label" for="inf-modelId">Model ID *</label>
      {#if modelIds.length}
        <select id="inf-modelId" bind:value={modelId} class="field-input">
          <option value="">— Select a model —</option>
          {#each modelIds as id}
            <option value={id}>{id}</option>
          {/each}
        </select>
      {:else}
        <input id="inf-modelId" type="text" required bind:value={modelId} class="field-input"
          placeholder="chest-xray-classifier-v1" />
      {/if}
    </div>

    <div>
      <div class="flex items-center justify-between mb-1.5">
        <label class="field-label mb-0" for="inf-input">Input Hash *</label>
        <button type="button" onclick={() => input = randomHash()}
          class="text-xs text-blue-600 hover:text-blue-800 font-medium">⟳ Generate</button>
      </div>
      <textarea id="inf-input" required rows={2} bind:value={input} class="field-input font-mono text-xs"
        placeholder="a1a1a1…"></textarea>
    </div>

    <div>
      <div class="flex items-center justify-between mb-1.5">
        <label class="field-label mb-0" for="inf-output">Output Hash *</label>
        <button type="button" onclick={() => outputHash = randomHash()}
          class="text-xs text-blue-600 hover:text-blue-800 font-medium">⟳ Generate</button>
      </div>
      <textarea id="inf-output" required rows={2} bind:value={outputHash} class="field-input font-mono text-xs"
        placeholder="d2d2d2…"></textarea>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <label class="field-label" for="inf-params">Parameters (JSON)</label>
        <textarea id="inf-params" rows={3} bind:value={params} class="field-input font-mono text-xs"
          placeholder="threshold, preprocessing..."></textarea>
      </div>
      <div>
        <label class="field-label" for="inf-meta">Metadata (JSON)</label>
        <textarea id="inf-meta" rows={3} bind:value={metadata} class="field-input font-mono text-xs"
          placeholder="dataset, framework..."></textarea>
      </div>
    </div>

    <button type="submit" disabled={loading} class="btn-primary w-full">
      {loading ? 'Logging…' : 'Execute & Log Inference'}
    </button>
  </form>

  {#if error}
    <div class="alert-error">{error}</div>
  {/if}

  {#if result}
    <div class="alert-success space-y-3">
      <h3 class="font-semibold text-emerald-800">✓ Inference Logged Successfully</h3>
      <dl class="text-sm text-emerald-700 space-y-1">
        <div><dt class="inline font-medium">Inference ID: </dt><dd class="inline">{result.inferenceId}</dd></div>
        <div><dt class="inline font-medium">Block: </dt><dd class="inline">#{result.blockIndex}</dd></div>
        <div><dt class="inline font-medium">Hash: </dt><dd class="inline font-mono text-xs break-all">{result.blockHash}</dd></div>
      </dl>
      {#if result.output}
        <div class="border-t border-emerald-200 pt-3">
          <div class="text-xs font-medium text-emerald-800 mb-1">Output</div>
          <pre class="bg-white/60 p-2 rounded text-xs overflow-x-auto text-emerald-900">{JSON.stringify(result.output, null, 2)}</pre>
        </div>
      {/if}
      {#if result.hashes}
        <div class="border-t border-emerald-200 pt-3 text-xs text-emerald-700 space-y-1">
          <div><strong>Input hash: </strong><code class="break-all">{result.hashes.input}</code></div>
          <div><strong>Output hash: </strong><code class="break-all">{result.hashes.output}</code></div>
        </div>
      {/if}
    </div>
  {/if}
</div>

// frontend/src/components/InferenceLogger.tsx
'use client';

import { useState, useEffect } from 'react';
import { logInference,getAllModelIds } from '@/lib/api';

interface Props {
  initialModelId?: string;
  onSuccess?: (modelId: string) => void;
}

export default function InferenceLogger({ initialModelId, onSuccess }: Props) {
  const [modelId, setModelId] = useState(initialModelId);

  const [formData, setFormData] = useState({
    modelId: initialModelId || '',
    inferenceId: 'f61c7b91-2e83-4f4a-8c9b-7c0cb90fca1e',
    input: 'a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
    outputHash: 'd2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2',
    params: '{"threshold": 0.8, "preprocessing": "normalize"}',
    metadata: '{"dataset": "ChestX-ray14", "framework": "TensorFlow", "author": "Dr. Smith"}',
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [modelIds, setModelIds] = useState<string[]>([]);

  useEffect(() => {
    async function fetchIds() {
      try {
        const ids = await getAllModelIds(); 
        setModelIds(ids);
      } catch {
        setModelIds([]);
      }
    }
    fetchIds();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const data = {
        modelId: formData.modelId,
        inferenceId: formData.inferenceId,
        inputHash: formData.input,
        outputHash: formData.outputHash,
        params: formData.params ? JSON.parse(formData.params) : {},
        metadata: formData.metadata ? JSON.parse(formData.metadata) : {},
      };

      const response = await logInference(data);
      setResult(response);

      if (onSuccess) onSuccess(formData.modelId);
    } catch (err: any) {
      setError(err.response?.data?.message || err.message || 'Failed to log inference');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Log Inference</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
          Execute and track an AI model inference on the blockchain
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Model ID *
          </label>
         
          <input
            type="text"
            required
            value={formData.modelId}
            onChange={(e) => setFormData({ ...formData, modelId: e.target.value })}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            placeholder="e.g., chest-xray-classifier-v1"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Input hash *
          </label>
          <textarea
            required
            value={formData.input}
            onChange={(e) => setFormData({ ...formData, input: e.target.value })}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white font-mono text-sm"
            rows={5}
            placeholder='a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1'
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Output hash *
          </label>
          <textarea
            required
            value={formData.outputHash}
            onChange={(e) => setFormData({ ...formData, outputHash: e.target.value })}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white font-mono text-sm"
            rows={5}
            placeholder='d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2'
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Parameters (JSON)
          </label>
          <textarea
            value={formData.params}
            onChange={(e) => setFormData({ ...formData, params: e.target.value })}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white font-mono text-sm"
            rows={3}
            placeholder='{"threshold": 0.8, "preprocessing": "normalize"}'
          />
        </div>

         <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Metadata (JSON)
          </label>
          <textarea
            value={formData.metadata}
            onChange={(e) => setFormData({ ...formData, metadata: e.target.value })}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white font-mono text-sm"
            rows={3}
            placeholder='{"dataset": "ChestX-ray14", "framework": "TensorFlow", "author": "Dr. Smith"}'
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full bg-primary hover:bg-primary/90 text-white font-medium py-3 px-6 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? 'Executing...' : 'Execute & Log Inference'}
        </button>
      </form>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
          <p className="text-red-800 dark:text-red-200 text-sm">{error}</p>
        </div>
      )}

      {result && (
        <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg p-4 space-y-3">
          <h3 className="font-semibold text-green-900 dark:text-green-100">
            ✅ Inference Logged Successfully!
          </h3>
          
          <div className="space-y-2 text-sm text-green-800 dark:text-green-200">
            <p><strong>Inference ID:</strong> {result.inferenceId}</p>
            <p><strong>Block Index:</strong> {result.blockIndex}</p>
            <p><strong>Block Hash:</strong> <code className="text-xs break-all">{result.blockHash}</code></p>
          </div>

          <div className="border-t border-green-200 dark:border-green-700 pt-3">
            <p className="font-semibold text-green-900 dark:text-green-100 mb-2">Output:</p>
            <pre className="bg-white dark:bg-gray-800 p-3 rounded text-xs overflow-x-auto">
              {JSON.stringify(result.output, null, 2)}
            </pre>
          </div>

          <div className="border-t border-green-200 dark:border-green-700 pt-3">
            <p className="font-semibold text-green-900 dark:text-green-100 mb-2">Hashes:</p>
            <div className="space-y-1 text-xs">
              <p><strong>Input Hash:</strong> <code>{result.hashes.input}</code></p>
              <p><strong>Output Hash:</strong> <code>{result.hashes.output}</code></p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
