// frontend/src/components/ProvenanceViewer.tsx
'use client';

import { useState, useEffect } from 'react';
import { getProvenance, verifyChain, getAllModelIds } from '@/lib/api';
import { format } from 'date-fns';

interface Props {
  initialModelId?: string;
}

export default function ProvenanceViewer({ initialModelId = '' }: Props) {
  const [modelId, setModelId] = useState(initialModelId);
  const [provenance, setProvenance] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [verifying, setVerifying] = useState(false);
  const [verification, setVerification] = useState<any>(null);
  const [modelIds, setModelIds] = useState<string[]>([]);

  useEffect(() => {
    if (initialModelId) {
      handleSearch();
    }
  }, [initialModelId]);

  useEffect(() => {
    async function fetchIds() {
      try {
        const ids = await getAllModelIds(); 
        setModelIds(ids);
      } catch {
        setModelIds([]);
      }
    }
    fetchIds();
  }, []);

  const handleSearch = async () => {
    if (!modelId.trim()) return;

    setLoading(true);
    setError(null);
    setProvenance(null);

    try {
      const data = await getProvenance(modelId);
      setProvenance(data);
    } catch (err: any) {
      setError(err.response?.data?.message || err.message || 'Failed to fetch provenance');
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async () => {
    setVerifying(true);
    try {
      const data = await verifyChain();
      setVerification(data);
    } catch (err: any) {
      setError(err.response?.data?.message || err.message || 'Failed to verify chain');
    } finally {
      setVerifying(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">View Provenance</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
          Query the complete audit trail of an AI model from the blockchain
        </p>
      </div>

      <div className="flex gap-3">
        <select
          value={modelId}
          onChange={e => setModelId(e.target.value)}
          required
          className="..."
        >
          <option value="">-- Select Model --</option>
          {modelIds.map(id => (
            <option key={id} value={id}>{id}</option>
          ))}
        </select>

        <input
          type="text"
          value={modelId}
          onChange={(e) => setModelId(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white"
          placeholder="Enter Model ID (e.g., chest-xray-classifier-v1)"
        />
        <button
          onClick={handleSearch}
          disabled={loading || !modelId.trim()}
          className="bg-primary hover:bg-primary/90 text-white font-medium py-2 px-6 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? 'Searching...' : 'Search'}
        </button>
        <button
          onClick={handleVerify}
          disabled={verifying}
          className="bg-secondary hover:bg-secondary/90 text-white font-medium py-2 px-6 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {verifying ? 'Verifying...' : 'Verify Chain'}
        </button>
      </div>

      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
          <p className="text-red-800 dark:text-red-200 text-sm">{error}</p>
        </div>
      )}

      {verification && (
        <div className={`border rounded-lg p-4 ${verification.isValid
            ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800'
            : 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800'
          }`}>
          <h3 className={`font-semibold mb-2 ${verification.isValid ? 'text-green-900 dark:text-green-100' : 'text-red-900 dark:text-red-100'
            }`}>
            {verification.isValid ? '✅ Chain is Valid' : '❌ Chain Verification Failed'}
          </h3>
          {verification.errors && verification.errors.length > 0 && (
            <ul className="list-disc list-inside text-sm text-red-800 dark:text-red-200">
              {verification.errors.map((err: string, i: number) => (
                <li key={i}>{err}</li>
              ))}
            </ul>
          )}
        </div>
      )}

      {provenance && (
        <div className="space-y-4">
          {/* Summary */}
          <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
            <h3 className="font-semibold text-blue-900 dark:text-blue-100 mb-3">
              📊 Provenance Summary
            </h3>
            <div className="grid grid-cols-3 gap-4 text-sm">
              <div>
                <p className="text-blue-600 dark:text-blue-300 font-medium">Model ID</p>
                <p className="text-blue-900 dark:text-blue-100">{provenance.modelId}</p>
              </div>
              <div>
                <p className="text-blue-600 dark:text-blue-300 font-medium">Total Blocks</p>
                <p className="text-blue-900 dark:text-blue-100">{provenance.totalBlocks}</p>
              </div>
              <div>
                <p className="text-blue-600 dark:text-blue-300 font-medium">Chain Valid</p>
                <p className={`font-bold ${provenance.chainValid ? 'text-green-600' : 'text-red-600'}`}>
                  {provenance.chainValid ? '✓ Yes' : '✗ No'}
                </p>
              </div>
            </div>
          </div>

          {/* History Timeline */}
          <div>
            <h3 className="font-semibold text-gray-900 dark:text-white mb-4">
              📜 History Timeline
            </h3>
            <div className="space-y-3">
              {provenance.history.map((event: any, index: number) => (
                <div
                  key={index}
                  className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 hover:shadow-md transition-shadow"
                >
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className="text-2xl">
                        {event.type === 'model_registration' ? '📝' : '🔬'}
                      </span>
                      <div>
                        <p className="font-semibold text-gray-900 dark:text-white">
                          {event.type === 'model_registration' ? 'Model Registration' : 'Inference'}
                        </p>
                        <p className="text-xs text-gray-500 dark:text-gray-400">
                          {format(new Date(event.timestamp), 'PPpp')}
                        </p>
                      </div>
                    </div>
                    <span className="text-xs bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">
                      Block #{event.blockIndex}
                    </span>
                  </div>

                  <div className="space-y-2 text-sm">
                    {event.version && (
                      <p className="text-gray-700 dark:text-gray-300">
                        <strong>Version:</strong> {event.version}
                      </p>
                    )}

                    {event.metadata && (
                      <div>
                        <p className="font-medium text-gray-700 dark:text-gray-300 mb-1">Metadata:</p>
                        <pre className="bg-gray-50 dark:bg-gray-800 p-2 rounded text-xs overflow-x-auto">
                          {JSON.stringify(event.metadata, null, 2)}
                        </pre>
                      </div>
                    )}

                    {event.params && Object.keys(event.params).length > 0 && (
                      <div>
                        <p className="font-medium text-gray-700 dark:text-gray-300 mb-1">Parameters:</p>
                        <pre className="bg-gray-50 dark:bg-gray-800 p-2 rounded text-xs overflow-x-auto">
                          {JSON.stringify(event.params, null, 2)}
                        </pre>
                      </div>
                    )}

                    {(event.inputHash || event.outputHash) && (
                      <div className="border-t border-gray-200 dark:border-gray-700 pt-2 mt-2">
                        {event.inputHash && (
                          <p className="text-xs text-gray-600 dark:text-gray-400">
                            <strong>Input Hash:</strong> <code>{event.inputHash}</code>
                          </p>
                        )}
                        {event.outputHash && (
                          <p className="text-xs text-gray-600 dark:text-gray-400">
                            <strong>Output Hash:</strong> <code>{event.outputHash}</code>
                          </p>
                        )}
                      </div>
                    )}

                    <p className="text-xs text-gray-500 dark:text-gray-400 font-mono break-all">
                      <strong>Block Hash:</strong> {event.blockHash}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {!provenance && !loading && !error && (
        <div className="text-center py-12 text-gray-500 dark:text-gray-400">
          <p className="text-lg">🔍 Enter a Model ID to view its provenance</p>
        </div>
      )}
    </div>
  );
}

// frontend-svelte/src/lib/components/ProvenanceViewer.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { format } from 'date-fns';
  import { getProvenance, verifyChain, getAllModelIds, exportProvenance, type ProvenanceFilter } from '$lib/api';

  let { initialModelId = '' }: { initialModelId?: string } = $props();

  let modelId      = $state(initialModelId ?? '');
  let provenance   = $state<any>(null);
  let loading      = $state(false);
  let error        = $state<string | null>(null);
  let verifying    = $state(false);
  let verification = $state<any>(null);
  let modelIds     = $state<string[]>([]);

  // Filters
  let filterType  = $state<'' | 'model_registration' | 'inference'>('');
  let filterFrom  = $state('');
  let filterTo    = $state('');

  onMount(async () => {
    try { modelIds = await getAllModelIds(); } catch { modelIds = []; }
    if (initialModelId) handleSearch();
  });

  async function handleSearch() {
    if (!modelId.trim()) return;
    loading = true; error = null; provenance = null;
    const filters: ProvenanceFilter = {};
    if (filterType) filters.type = filterType;
    if (filterFrom) filters.from = filterFrom;
    if (filterTo)   filters.to   = filterTo;
    try {
      provenance = await getProvenance(modelId, filters);
    } catch (err: any) {
      error = err.message || 'Failed to fetch provenance';
    } finally {
      loading = false;
    }
  }

  async function handleVerify() {
    verifying = true;
    try {
      verification = await verifyChain();
    } catch (err: any) {
      error = err.message || 'Failed to verify chain';
    } finally {
      verifying = false;
    }
  }

  function handleExport() {
    window.open(exportProvenance(modelId), '_blank');
  }
</script>

<div class="max-w-3xl space-y-6">
  <div>
    <h2 class="text-xl font-semibold text-slate-800">View Provenance</h2>
    <p class="text-sm text-slate-500 mt-1">Query the complete audit trail of a model from the blockchain</p>
  </div>

  <!-- Model selector + actions -->
  <div class="flex gap-2 flex-wrap">
    {#if modelIds.length}
      <select bind:value={modelId} class="field-input flex-1 min-w-0">
        <option value="">— Select a model —</option>
        {#each modelIds as id}
          <option value={id}>{id}</option>
        {/each}
      </select>
    {:else}
      <input type="text" bind:value={modelId}
        onkeydown={(e) => e.key === 'Enter' && handleSearch()}
        class="field-input flex-1" placeholder="Enter Model ID…" />
    {/if}
    <button onclick={handleSearch} disabled={loading || !modelId.trim()} class="btn-primary">
      {loading ? 'Searching…' : 'Search'}
    </button>
    <button onclick={handleVerify} disabled={verifying} class="btn-secondary">
      {verifying ? 'Verifying…' : 'Verify Chain'}
    </button>
    {#if provenance}
      <button onclick={handleExport} class="btn-outline" title="Download as JSON">
        ⬇ Export
      </button>
    {/if}
  </div>

  <!-- Filters -->
  <details class="card">
    <summary class="px-5 py-3 text-sm font-medium text-slate-600 cursor-pointer select-none hover:bg-slate-50 rounded-xl">
      🔎 Filters
      {#if filterType || filterFrom || filterTo}
        <span class="ml-2 text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full">active</span>
      {/if}
    </summary>
    <div class="px-5 pb-5 pt-3 grid grid-cols-1 sm:grid-cols-3 gap-4 border-t border-slate-100">
      <div>
        <label class="field-label" for="prov-type">Event type</label>
        <select id="prov-type" bind:value={filterType} class="field-input text-sm">
          <option value="">All types</option>
          <option value="model_registration">Registration</option>
          <option value="inference">Inference</option>
        </select>
      </div>
      <div>
        <label class="field-label" for="prov-from">From</label>
        <input id="prov-from" type="date" bind:value={filterFrom} class="field-input text-sm" />
      </div>
      <div>
        <label class="field-label" for="prov-to">To</label>
        <input id="prov-to" type="date" bind:value={filterTo} class="field-input text-sm" />
      </div>
    </div>
    <div class="px-5 pb-4 flex gap-2">
      <button onclick={handleSearch} disabled={!modelId.trim() || loading} class="btn-primary text-sm py-2">
        Apply filters
      </button>
      <button onclick={() => { filterType = ''; filterFrom = ''; filterTo = ''; handleSearch(); }}
        class="btn-outline text-sm py-2">
        Clear
      </button>
    </div>
  </details>

  {#if error}
    <div class="alert-error">{error}</div>
  {/if}

  {#if verification}
    <div class="rounded-lg p-4 border {verification.isValid
      ? 'bg-emerald-50 border-emerald-200'
      : 'bg-red-50 border-red-200'}">
      <p class="font-semibold text-sm {verification.isValid ? 'text-emerald-800' : 'text-red-800'}">
        {verification.isValid ? '✓ Chain is Valid' : '✗ Chain Verification Failed'}
      </p>
      {#if verification.errors?.length}
        <ul class="mt-2 text-sm text-red-700 list-disc list-inside space-y-1">
          {#each verification.errors as err}
            <li>{err}</li>
          {/each}
        </ul>
      {/if}
    </div>
  {/if}

  {#if provenance}
    <!-- Summary pills -->
    <div class="grid grid-cols-3 gap-4">
      {#each [
        { label: 'Model ID',     value: provenance.modelId,     mono: true },
        { label: 'Total Blocks', value: provenance.totalBlocks },
        { label: 'Chain Valid',
          value: provenance.chainValid ? '✓ Yes' : '✗ No',
          color: provenance.chainValid ? 'text-emerald-600' : 'text-red-600' }
      ] as pill}
        <div class="card p-4">
          <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">{pill.label}</div>
          <div class="text-sm font-semibold {pill.color ?? 'text-slate-800'} {pill.mono ? 'font-mono truncate' : ''}">
            {pill.value}
          </div>
        </div>
      {/each}
    </div>

    <!-- Timeline -->
    <div>
      <h3 class="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-4">History Timeline</h3>
      <div class="space-y-3">
        {#each provenance.history as event, i (i)}
          <div class="card p-5">
            <div class="flex items-start justify-between mb-3">
              <div class="flex items-center gap-3">
                <div class="w-8 h-8 rounded-full flex items-center justify-center text-sm flex-shrink-0
                  {event.type === 'model_registration' ? 'bg-blue-100 text-blue-600' : 'bg-sky-100 text-sky-600'}">
                  {event.type === 'model_registration' ? '📝' : '🔬'}
                </div>
                <div>
                  <p class="font-medium text-slate-800 text-sm">
                    {event.type === 'model_registration' ? 'Model Registration' : 'Inference'}
                  </p>
                  <p class="text-xs text-slate-400">{format(new Date(event.timestamp), 'dd MMM yyyy · HH:mm:ss')}</p>
                </div>
              </div>
              <span class="text-xs bg-slate-100 text-slate-500 px-2 py-1 rounded-full">Block #{event.blockIndex}</span>
            </div>

            <div class="space-y-2.5 text-sm">
              {#if event.version}
                <div class="text-slate-600"><span class="font-medium">Version:</span> {event.version}</div>
              {/if}
              {#if event.metadata}
                <div>
                  <div class="text-xs font-medium text-slate-500 uppercase tracking-wider mb-1">Metadata</div>
                  <pre class="bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs overflow-x-auto text-slate-600">{JSON.stringify(event.metadata, null, 2)}</pre>
                </div>
              {/if}
              {#if event.params && Object.keys(event.params).length}
                <div>
                  <div class="text-xs font-medium text-slate-500 uppercase tracking-wider mb-1">Parameters</div>
                  <pre class="bg-slate-50 border border-slate-200 rounded-lg p-2 text-xs overflow-x-auto text-slate-600">{JSON.stringify(event.params, null, 2)}</pre>
                </div>
              {/if}
              {#if event.inputHash || event.outputHash}
                <div class="border-t border-slate-100 pt-2 space-y-1">
                  {#if event.inputHash}
                    <div class="text-xs text-slate-500"><span class="font-medium">Input Hash:</span> <code class="font-mono">{event.inputHash}</code></div>
                  {/if}
                  {#if event.outputHash}
                    <div class="text-xs text-slate-500"><span class="font-medium">Output Hash:</span> <code class="font-mono">{event.outputHash}</code></div>
                  {/if}
                </div>
              {/if}
              <div class="text-xs text-slate-400 font-mono break-all border-t border-slate-100 pt-2">
                <span class="font-medium not-italic text-slate-500">Block Hash:</span> {event.blockHash}
              </div>
            </div>
          </div>
        {/each}
      </div>
    </div>

  {:else if !loading && !error}
    <div class="card py-16 text-center text-slate-400">
      <div class="text-3xl mb-3">🔍</div>
      <p class="text-sm">Select a model or enter an ID to view its provenance trail</p>
    </div>
  {/if}
</div>
